name: frepo
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.6
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - fire=0.4.0
  - imageio=2.22.0
  - einops=0.4.1
  - jupyterhub=3.0.0
  - jupyter_contrib_nbextensions=0.5.1
  - pip
  - pip:
      - tensorflow~=2.10
      - tensorflow-datasets~=4.7.0
      - -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html "jax[cuda]"
      - flax~=0.6.1
      - optax~=0.1.3
      - clu~=0.0.7
      - ml_collections~=0.1.1
      - tensorflow-privacy~=0.8.5